- name: Install ruby
  yum:
   name: ruby
   state: latest
- name: Install gems
  yum:
   name: rubygems
   state: latest
- name: Ensure nginx is installed and latest version
  yum:
   name: nginx
   state: latest
  when: (ansible_distribution == "CentOS")
- name: Update repositories if cache is older then 5 days
  apt:
    update_cache: yes
    cache_valid_time: 43200
  when: (ansible_distribution == "Ubuntu")
- name: Ensure nginx is installed and latest version
  apt:
   name: nginx
   state: latest
  when: (ansible_distribution == "Ubuntu")
- name: Create nginx user if not there
  user:
    name: nginx
    comment: Nginx web server
    shell: /sbin/nologin
    home: /var/lib/nginx
    state: present
  when: (ansible_distribution == "Ubuntu")
- name: Create index.html
  copy:
    content: "{{ docdata }}"
    dest: "{{ docroot }}/index.html"
- name: Set the core config
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
- name: Set root config
  template:
    src: "{{ role_path }}/templates/conf-default.conf.j2"
    dest: /etc/nginx/conf.d/default.conf
- name: Ensure nginx is started
  service:
    name: nginx
    state: started
    enabled: yes
- name: Some user accounts
  user:
    name: "{{ item.username }}"
    shell: "{{ item.program }}"
    home: "{{ item.homedir }}"
    state: present
  with_items:
    - { username: 'steve', program: '/bin/bash', homedir: '/home/steve' }
    - { username: 'bob', program: '/bin/zsh', homedir: '/home/bob' }
    - { username: 'kris', program: '/bin/bash', homedir: '/home/kris' }
