- name: Display attributes
  debug:
    msg:
      - "SSH Key: {{ ansible_ssh_private_key_file }}"
      - "User: {{ ansible_ssh_user }}"
      - "SSH Args: {{ ansible_ssh_common_args }}"

- name: Create ec2 instance
  ec2:
    key_name: "{{ sshkey }}"
    group: "{{ ec2SG }}"
    instance_type: t2.micro
    image: ami-017b0e29fac27906b
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ ec2subnet }}"
    assign_public_ip: yes
    instance_tags:
      Name: StevesVault
      Environment: "{{ env }}"
  when: groups['vault'] | length == 0
  register: ec2vault

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 30
    timeout: 320
  when: groups['vault'] | length == 0
  with_items: "{{ ec2vault.instances }}"

- name: Add to inventory
  lineinfile:
    dest: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    insertafter: '^\[vault\]'
    line: "{{ item.public_dns_name }}"
  when: groups['vault'] | length == 0
  with_items: "{{ ec2vault.instances }}"

- name: Refresh inventory
  meta: refresh_inventory
