- name: Install NGINX web server
  apt:
    name: nginx
    state: installed
- name: Check NGINX is started and start it if not
  service:
    name: nginx
    enabled: yes
    state: started
  ignore_errors: yes
- name: Apply NGINX configuration
  template:
    src: templates/nginx/sites-available/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
