- name: Create ec2 instance for Kubernetes
  ec2:
    key_name: "{{ sshkey }}"
    group: "{{ ec2SG }}"
    instance_type: t2.micro
    image: "{{ ami[region] }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ ec2subnet }}"
    assign_public_ip: yes
    instance_tags: "{{ mytags }}"
  when: groups['kube'] | length == 0
  register: ec2instance

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 30
    timeout: 120
  when: groups['kube'] | length == 0
  with_items: "{{ ec2instance.instances }}"

- name: Add to inventory
  lineinfile:
    dest: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    insertafter: '^\[kube\]'
    line: "{{ item.public_dns_name }} instance_id={{ item.id}}"
  when: groups['kube'] | length == 0
  with_items: "{{ ec2instance.instances }}"

- name: Refresh inventory
  meta: refresh_inventory
