- name: Install nano
  yum:
    name: nano
    state: latest
- name: SSH config
  copy:
    src: files/.ssh_config
    dest: /home/ec2-user/.ssh/config
    owner: ec2-user
    group: ec2-user
    mode: 0600
