- name: DEBUG
  debug:
    msg: "HOSTVAR: {{hostvars[inventory_hostname].systemname}}"

- name: Install Logstash
  package:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-7.5.1.rpm
    state: present
  when: hostvars[inventory_hostname].systemname == "{{prefix}}VMlogstash"

- name: Install Kibana
  package:
    name: https://artifacts.elastic.co/downloads/kibana/kibana-7.5.1-x86_64.rpm
    state: present
  when: hostvars[inventory_hostname].systemname == "{{prefix}}VMkibana"

- name: Install elasticsearch
  package:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-x86_64.rpm
    state: present
  when: hostvars[inventory_hostname].systemname == "{{prefix}}VMelastic"

- name: Configure Elasticsearch
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch.yml
    owner: root
    group: root
    mode: 0640

- name: Start service Logstash
  service:
    name: logstash
    state: started
    enabled: yes
  when: hostvars[inventory_hostname].systemname == "{{prefix}}VMlogstash"

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes
  when: hostvars[inventory_hostname].systemname == "{{prefix}}VMkibana"

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: hostvars[inventory_hostname].systemname == "{{prefix}}VMelastic"
