- name: Install dependant software
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - unzip
    - wget

- name: Install Vault
  unarchive:
    src: https://releases.hashicorp.com/vault/0.11.4/vault_0.11.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Configure Vault
  copy:
    src: vault.cfg
    dest: /usr/local/etc/vault.cfg
    mode: 0644
    owner: root
    group: root

- name: Generate a Self Signed OpenSSL certificate
  shell: >
    openssl req -new -subj "/CN={{ inventory_hostname }}" -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out vault.crt -keyout vault.key
  args:
    chdir: /usr/local/etc

- name: Create init script
  copy:
    src: init-vault
    dest: /etc/init.d/vault
    owner: root
    group: root
    mode: 0755

- name: Start Vault
  service:
    name: vault
    state: started
    enabled: yes
