- name: Remove s3 Bucket
  aws_s3:
    bucket: stevessecretbucket
    mode: delete

- name: Remove RDS
  rds:
    command: delete
    instance_name: "{{ dbname }}"
    region: "{{ region }}"

- debug:
    var: "{{ item }}"
  with_items: groups['php']

- set_fact:
    phpsrv: groups['php'][0]

- debug:
    var: "{{ phpsrv }}"

- name: PHP facts
  ec2_instance_facts:
    filters:
      "tag:Name": "StevesPHP"
    region: "{{ region }}"
  register: ec2instance

- debug:
    var: ec2instance.instances[0].network_interfaces[0].association.public_dns_name

# - debug:
#     var: ec2instance.instances[0].instance_id

- name: Remove PHP server
  ec2:
    state: absent
    instance_ids: "{{ ec2instance.instances[0].instance_id }}"
    region: "{{ region }}"

- name: remove PHP server from inventory
  lineinfile:
     dest: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
     state: absent
     regexp: "{{ ec2instance.network_interfaces[0].association.public_dns_name }}"
