- hosts: webservers
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: installed
  - name: Create default index.html file
    blockinfile:
      path: /var/www/html/index.html
      create: yes
      block: |
        <html>
        <h1>Congratulations you have done Ansible</h1>
        </html>
  - name: Start Apache
    service:
      name: httpd
      enabled: yes
      state: started
