- name: Install extra software
  package:
    name:
      - git
      - '@Development tools'
      - python2-pip

- name: Install Python jenkins module
  pip:
    name: "{{ item }}"
  with_items:
    - python-jenkins
