# Create a throw away key pair to create the instance
- name: Create Key Pair
  ec2_key:
    name: "{{ keyname }}"
    region: "{{ region }}"
    state: present
  register: ec2key

- debug:
    msg: "{{ ec2key.key.private_key }}"
  ignore_errors: yes

- name: Write the key to local machine
  copy:
    dest: "{{ playbook_dir }}/{{ keyname }}.pem"
    content: "{{ ec2key.key.private_key }}"
    mode: 0600
  when: ec2key.key.private_key is defined

- name: Create ec2 instance
  ec2:
    key_name: "{{ keyname }}"
    group: "{{ ec2SG }}"
    instance_type: t2.micro
    image: ami-017b0e29fac27906b
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ ec2subnet }}"
    assign_public_ip: yes
    instance_tags:
      Name: Stevespetclinic
      Environment: "{{ env }}"
  when: groups['petclinic'] | length == 0
  register: ec2petclinic

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 30
    timeout: 320
  when: groups['petclinic'] | length == 0
  with_items: "{{ ec2petclinic.instances }}"

- name: Add to inventory
  lineinfile:
    dest: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    insertafter: '^\[petclinic\]'
    line: "{{ item.public_dns_name }}"
  when: groups['petclinic'] | length == 0
  with_items: "{{ ec2petclinic.instances }}"

- name: Refresh inventory
  meta: refresh_inventory
