- name: Destroy LB
  elb_application_lb:
    name: "steve-k8s-{{ ec2env }}-lb"
    state: absent

- name: Destroy Target Group
  elb_target_group:
    name: "steve-k8s-{{ ec2env }}-tg"
    state: absent

- name: Remove ELB from inventory
  lineinfile:
    path: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    regexp: "^{{item}}"
    state: absent
  with_items: "{{ groups['ELB'] }}"
  when: "'ELB' not in groups"

- name: Remove ELB Group from inventory
  lineinfile:
    path: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    regexp: "^[ELB]"
    state: absent
  when: "'ELB' not in groups"
