- name: Destroy LB
  elb_application_lb:
    name: "steve-k8s-{{ ec2env }}-lb"
    region: "{{ region }}"
    wait: yes
    state: absent

- name: Destroy Target Group
  elb_target_group:
    name: "steve-k8s-{{ ec2env }}-tg"
    protocol: http
    vpc_id: "{{ vpc_id[region] }}"
    port: "{{hostvars[item].lbport}}"
    state: absent
    region: "{{ region }}"
  with_items: "{{ groups['ELB'] }}"

- name: Check master record
  route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{ dnszoneid }}"
    start_record_name: "*.app.{{dnsprefix}}.{{dnszone}}"
  register: lbdns

- name: Remove Master DNS entries
  route53:
    state: absent
    zone: "{{ dnszone }}"
    record: "*.app.{{dnsprefix}}.{{ dnszone }}"
    type: CNAME
    ttl: 60
    value:
      - "{{ groups['ELB'][0] }}"
  when: lbdns is defined

- name: Remove ELB from inventory
  lineinfile:
    path: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    regexp: "^{{item}}"
    state: absent
  with_items: "{{ groups['ELB'] }}"
  when: "'ELB' in groups"

- name: Remove ELB Group from inventory
  lineinfile:
    path: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    regexp: "^[ELB]"
    state: absent
  ignore_errors: true

- name: Refresh ELB inventory
  meta: refresh_inventory
