- hosts: ec2
  connection: local
  gather_facts: false
  roles:
    - ec2

- hosts: jenkins
  become: True
  gather_facts: True
  roles:
    - role: jenkins-apps
      become: yes
    - role: ansible-role-java
      become: yes
    - role: ansible-role-jenkins
      become: yes
    - role: jenkins-jobs
