- name: Install epel
  yum:
    name: epel-release
    state: latest
- name: Install Ansible
  pip:
    name: ansible
- name: Copy SSH private key
  copy:
    src: ~/.ssh/academy_jan_2018.pem
    dest: /home/ec2-user/.ssh/id_rsa
    owner: ec2-user
    group: ec2-user
    mode: 0600
