- name: restart apache
  service:
    name: httpd
    state: restarted
  when: (ansible_distribution == "CentOS")
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: (ansible_distribution == "Ubuntu")
