- hosts: s3
  connection: local
  gather_facts: false
  roles:
    - s3

- hosts: rds
  connection: local
  gather_facts: false
  roles:
    - rds

- hosts: remove
  connection: local
  gather_facts: false
  roles:
    - destroy

- hosts: ec2
  connection: local
  gather_facts: false
  roles:
    - phpserver

- hosts: php
  become: True
  gather_facts: True
  roles:
    - phpprovision
