- name: Add Window Desktop files to applications
  copy:
    src: "{{ item }}"
    dest: "/usr/share/applications/{{ item | basename }}"
  with_fileglob: files/application.desktop/*

- name: Create the autostart directory for Steve
  file:
    path: /home/steve/.config/autostart
    state: directory
    mode: 0755

- name: Add Start Up files to Steve
  copy:
    src: "{{ item }}"
    dest: "/home/steve/.config/autostart/{{ item | basename }}"
  with_fileglob: files/steve.autostart/*

- name: Root cron
  copy:
    src: "{{ role_path }}/files/server/cron_root"
    dest: /var/spool/cron/root
    mode: 0600
    owner: root
    group: root

- name: Steve cron
  copy:
    src: "{{ role_path }}/files/server/cron_steve"
    dest: /var/spool/cron/steve
    owner: steve
    group: steve
    mode: 0600

- name: Set servers X11 configuration
  copy:
    src: "{{ role_path }}/files/server/xorg.conf"
    dest: /etc/X11/xorg.conf
    mode: 0644
    owner: root
    group: root
  when: ansible_all_ipv4_addresses[0] == server_ip

- name: Set server X11 config directory
  copy:
    src: "{{ role_path }}/files/server/xorg.conf.d/"
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
  when: ansible_all_ipv4_addresses[0] == server_ip

- name: Set youtube-dl link
  file:
    state: link
    src: /home/steve/Documents/projects/Software/youtube-dl/youtube-dl
    dest: /usr/bin/youtube-dl
    owner: root
    group: root

- name: Set iplayer link
  file:
    state: link
    src: /home/steve/Documents/projects/Software/get_iplayer/get_iplayer
    dest: /usr/bin/get_iplayer
    owner: root
    group: root

- name: Stop cgroup issue with Docker
  shell:
    - dnf install -y grubby
    - grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
