- name: Password Gorilla
  get_url:
    url: https://gorilla.dp100.com/downloads/gorilla1537_64.bin
    dest: /usr/local/bin/gorilla1537_64.bin
    mode: 0755
    owner: root
    group: root
    validate_certs: no

- name: Install AWSCLI todos
  debug:
    msg:
      - pip install awscli
      - laptop = xorg-x11-drv-ati and xorg-x11-drv-intel
