- name: Password Gorilla
  get_url:
    url: https://gorilla.dp100.com/downloads/gorilla1537_64.bin
    dest: /usr/local/bin/gorilla1537_64.bin
    mode: 0755
    owner: root
    group: root
    validate_certs: no

- name: Install AWSCLI todos
  debug:
    msg:
      - pip install awscli
      - laptop = xorg-x11-drv-ati and xorg-x11-drv-intel

- name: Install OpenShift CLI
  unarchive:
    src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
