- name: Add Steve user
  user:
    name: steve
    uid: 1000
    comment: steve
    group: steve
    groups: wheel,vboxsf,vboxusers,docker,pkg-build
    create_home: no
    home: /home/steve
    state: present

- name: Add Tara group
  group:
    name: tara
    gid: 1002
    state: present

- name: Add Tara user
  user:
    name: tara
    uid: 1001
    comment: tara
    group: tara
    create_home: no
    home: /home/tara
    state: present

- name: Add Steve to sudoers
  copy:
    src: "{{ role_path }}/files/steve.conf"
    dest: /etc/sudoers.d/steve.conf
    owner: root
    group: root
    mode: "0644"
