- name: System update
  shell: yum -y update

- name: Install dependency software
  yum:
    state: present
    name:  "{{ item }}"
  with_items: "{{ dependent_sw }}"

# Get hosts private IP for eth0 and public IP
- name: Get hosts private IP
  uri:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    return_content: yes
  register: private_ip_addr

- name: Get hosts public IP
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    return_content: yes
  register: public_ip_addr

- name: Setting IP addresses
  set_fact:
    private_ip: "{{ private_ip_addr.content }}"
    public_ip:  "{{ public_ip_addr.content }}"

- debug:
    msg:
      - "Public IP: {{ public_ip }}"
      - "Private IP {{ private_ip }}"

- name: Set the docker insecure registry
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: '^INSECURE_REGISTRY'
    line: INSECURE_REGISTRY='--insecure-registry "{{ private_ip.split('.')[0] }}.{{private_ip.split('.')[1]}}".0.0/16'

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Install openshift
  unarchive:
    remote_src: yes
    src: https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz
    dest: /tmp
    owner: root
    group: root
    exclude:
      - LICENSE
      - README.md

- name: Move files to /usr/local/sbin
  shell: mv openshift-origin-server-v1.4.1+3f9807a-linux-64bit/* /usr/local/sbin
  args:
    chdir: /tmp/

- name: Openshift start/stop script
  template:
    dest: /usr/local/bin/start_openshift.sh
    src: templates/start_openshift.sh.j2
    owner: root
    group: root
    mode: 0755
    force: yes

- name: Copy Openshift service file
  copy:
    src: openshift.service
    dest: /etc/systemd/system/openshift.service
    owner: root
    group: root
    mode: 0755

- name: Make Openshift directory
  file:
    path: /opt/openshift
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Systemd Daemon reload
  systemd:
    daemon_reload: yes

- name: Start Openshift
  systemd:
    name: openshift
    state: restarted
    enabled: yes

- name: Check if firewalld is active
  shell: which firewall-cmd
  ignore_errors: yes
  register: fwd

- name: Firewall ports allowed
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    zone: public
  with_items: "{{ allowed_ports }}"
  when: fwd is success

- name: Set root environment variables
  lineinfile:
    path: /root/.bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'KUBECONFIG', line: 'export KUBECONFIG=/opt/openshift/openshift.local.config/master/admin.kubeconfig' }
    - { regexp: 'CURL_CA', line: 'export CURL_CA_BUNDLE=/opt/openshift/openshift.local.config/master/ca.crt' }

- name: Copy up shell script to configure Openshift
  copy:
    src: oc.sh
    dest: /root/oc.sh
    owner: root
    group: root
    mode: 0755

- name: Execute oc commands to complete install
  shell: /root/oc.sh

- name: Add web user
  user:
    name: admin
    comment: OC Admin
    create_home: no
    password: "{{ admin_password | password_hash('sha512') }}"
