---
- hosts: puppet
  become: true
  become_user: root
  roles:
    - puppetserver

- hosts: jenkins
  become: true
  become_user: root
  roles:
    - jenkinsserver

- hosts: webserver
  become: true
  become_user: root
  roles:
    - webserver
