- name: Install dependant software
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - java-1.8.0-openjdk
    - wget

- name: Create petclinic directory
  file:
    path: /opt/petclinic
    state: directory
    mode: 0755
    recurse: yes

- name: Copy jar from Jenkins to instance
  copy:
    dest: "/opt/petclinic/{{ item }}"
    src: "{{ playbook_dir }}/../../target/{{ item }}"
  with_items:
    - spring-petclinic-2.0.0.jar
    - spring-petclinic-2.0.0.jar.original

- name: Create init script
  copy:
    src: init-petclinic
    dest: /etc/init.d/petclinic
    owner: root
    group: root
    mode: 0755

- name: Start petclinic
  service:
    name: petclinic
    state: started
    enabled: yes
  ignore_errors: yes
# Petclinic won't start properly unless database is present
