- name: Install haproxy
  yum:
    name: haproxy
    state: installed
- name: Copy config file
  template:
    dest: /etc/haproxy/haproxy.cfg
    src: templates/haproxy.cfg.j2
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
    - restart haproxy
- name: Start haproxy
  service:
    name: haproxy
    state: started
