- name: Install Jenkins dependencies
  yum:
    name: ["java-1.8.0-openjdk", "java-1.8.0-openjdk-devel", "git"]
    state: present

- name: Install Maven
  unarchive:
    src: "{{ mavenurl }}"
    dest: /opt
    remote_src: yes

- name: Set Maven in path
  copy:
    dest: /etc/profile.d/mvn.sh
    content: export PATH=$PATH:/opt/apache-maven-3.6.0/bin

- name: Download Jenkins repo key
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins gpg key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: installed

- name: Initial Jenkins start
  service:
    name: jenkins
    state: started

- name: Wait for Jenkins to start
  wait_for:
    path: /var/log/jenkins/jenkins.log
    search_regex: "Jenkins is fully up and running"

- name: Stop Jenkins to create admin user
  service:
    name: jenkins
    state: stopped

- name: Set Admin password
  shell: echo -n '{{ adminpw }}' | sha256sum
  register: adminpass

- set_fact:
    jpass: adminpass.output

- name: Set log file to blank
  copy:
    content: ""
    dest: /var/log/jenkins/jenkins.log
    force: yes
    owner: jenkins
    group: jenkins
    mode: 0644

# - name: Remove temp admin account
#   command: rm -rf /var/lib/jenkins/users/admin_*
#   ignore_errors: true
- name: Remove temp admin account
  file:
    path: /var/lib/jenkins/users
    state: absent
    force: yes
  ignore_errors: true

- name: Make new directory
  file:
    path: /var/lib/jenkins/users
    owner: jenkins
    group: jenkins
    mode: 0755
  ignore_errors: true

- name: Create admin user directory
  file:
    path: /var/lib/jenkins/users/admin
    state: directory
    mode: 0755
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Change the Jenkins user
  copy:
    src: files/users.xml
    dest: /var/lib/jenkins/users/users.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Set Jenkins Admin
  template:
    src: admin-config.xml.j2
    dest: /var/lib/jenkins/users/admin/config.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Set Jenkins config to not initial
  copy:
    src: files/config.xml
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Initial Jenkins start
  service:
    name: jenkins
    state: started

- name: Wait for Jenkins to restart
  wait_for:
    path: /var/log/jenkins/jenkins.log
    search_regex: "Jenkins is fully up and running"

- name: Wait for Jenkins URL
  uri:
    url: "http://{{ groups['jenkins'][0] }}:8080"
    status_code: 403
    timeout: 5
    user: admin
    password: "{{ adminpw }}"
  register: jenkinsURL
  retries: 60
  delay: 5
  until: >
    'status' in jenkinsURL and jenkinsURL['status'] == 403

- name: Debug URL
  debug:
    msg: "{{ jenkinsURL }}"

- name: Install Jeknins Plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: "{{ adminpw }}"
  with_items:
    - build-timeout
    - credentials-bindings
    - ws-cleanup
    - ant
    - gradle
    - github-branch-source
    - git
    - subversion
    - ssh-slaves
    - matrix-auth
    - pam-auth
    - ldap
    - email-ext
    - mailer
