- name: Create ec2 instance
  ec2:
    key_name: "{{ sshkey }}"
    group: "{{ ec2SG }}"
    instance_type: t2.micro
    image: ami-017b0e29fac27906b
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ ec2subnet }}"
    assign_public_ip: yes
    instance_tags:
      Name: StevesPHP
      Environment: "{{ env }}"
  when: groups['php'] | length == 0
  register: ec2php

# - name: Add new instance to host group
#   add_host:
#     hostname: "{{ item.public_ip }}"
#     groupname: launched
#   when: groups['php'] | length == 0
#   with_items: "{{ ec2php.instances }}"

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  when: groups['php'] | length == 0
  with_items: "{{ ec2php.instances }}"

- name: Add to inventory
  lineinfile:
    dest: "{{ playbook_dir }}/environments/{{ ec2env }}/hosts"
    insertafter: '^\[php\]'
    line: "{{ item.public_dns_name }}"
  when: groups['php'] | length == 0
  with_items: "{{ ec2php.instances }}"

- name: Refresh inventory
  meta: refresh_inventory
